# Generated by Django 4.0.6 on 2022-07-25 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('TG_BOT', 'Telegram Bot'), ('CUSTOM', 'Custom')], max_length=32)),
                ('text', models.TextField()),
                ('round', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankie.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game result',
                'verbose_name_plural': 'Games results',
                'db_table': 'game_result',
                'default_related_name': 'game_results',
                'unique_together': {('player', 'game', 'text')},
            },
        ),
        migrations.CreateModel(
            name='GameRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('py_class', models.CharField(max_length=256)),
                ('py_kwargs', models.JSONField(default={})),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankie.game')),
            ],
            options={
                'verbose_name': 'Game rule',
                'verbose_name_plural': 'Game rules',
                'db_table': 'game_rule',
                'default_related_name': 'rules',
                'unique_together': {('game', 'name')},
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_leagues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'db_table': 'league',
                'default_related_name': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankie.league')),
                ('mvp', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Rounds',
                'db_table': 'round',
                'default_related_name': 'rounds',
                'unique_together': {('label', 'league')},
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('mvp_count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankie.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Standing',
                'verbose_name_plural': 'Standings',
                'db_table': 'standing',
                'default_related_name': 'standings',
                'unique_together': {('player', 'league')},
            },
        ),
        migrations.AddField(
            model_name='league',
            name='players',
            field=models.ManyToManyField(through='rankie.Standing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankie.gamerule'),
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankie.gameresult')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankie.round')),
            ],
            options={
                'verbose_name': 'Round result',
                'verbose_name_plural': 'Rounds results',
                'db_table': 'round_result',
                'default_related_name': 'round_results',
                'unique_together': {('round', 'player')},
            },
        ),
    ]
