# Generated by Django 4.0.6 on 2022-07-25 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='round',
        ),
    ]
