# Generated by Django 4.0.6 on 2022-07-24 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rankie', '0002_game_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='end_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='start_dt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('user', 'league')},
        ),
    ]
