# Generated by Django 4.0.6 on 2022-07-27 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankie', '0002_remove_gameresult_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerule',
            name='py_kwargs',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='LeagueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_type', models.CharField(choices=[('default', 'Default')], max_length=32)),
                ('context', models.JSONField(default=dict)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankie.league')),
            ],
            options={
                'verbose_name': 'League event',
                'verbose_name_plural': 'League events',
                'db_table': 'league_event',
                'default_related_name': 'events',
            },
        ),
    ]
