# Generated by Django 4.0.6 on 2022-07-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankie', '0003_alter_gamerule_py_kwargs_leagueevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
