# Generated by Django 4.0.6 on 2022-07-27 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rankie', '0004_league_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
