# Generated by Django 4.0.6 on 2022-07-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankie', '0005_leagueevent_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueevent',
            name='ev_type',
            field=models.CharField(choices=[('NEW_LEADER', 'New Leader'), ('NEW_SCORE', 'New Score'), ('NEW_PLAYER', 'New Player'), ('NEW_MVP', 'New Mvp'), ('PLAYER_LEFT', 'Player Left'), ('LEAGUE_FINISHED', 'League Finished')], max_length=32),
        ),
    ]
