# Generated by Django 4.0.6 on 2022-08-02 11:34

import apps.rankie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankie', '0006_alter_leagueevent_ev_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='parser_regex',
            field=models.TextField(default='', validators=[apps.rankie.models.GameParserValidator(['game', 'round', 'score'])]),
            preserve_default=False,
        ),
    ]
