# Generated by Django 4.0.6 on 2022-08-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankie', '0007_game_parser_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerule',
            name='py_kwargs',
            field=models.JSONField(default={}),
        ),
    ]
